# Generated by Django 4.2.4 on 2023-09-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(max_length=200)),
                ('data_publi', models.DateTimeField(verbose_name='Data publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_feedback', models.CharField(max_length=50)),
                ('texto_feedback', models.CharField(max_length=200)),
                ('data_publi', models.DateTimeField(verbose_name='Data da publicação')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
