# Generated by Django 4.2.4 on 2023-09-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data_publi',
            field=models.CharField(max_length=200),
        ),
    ]
