# Generated by Django 4.2.4 on 2023-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_data_publi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='titulo_feedback',
            field=models.TextField(),
        ),
    ]
